### ISSUE TITLE
Unable to create memory cards

### ISSUE THREAD

**Issue by Mew-Lew** [SternXD/XBSX2#4]
**Description:** I'm experiencing an issue with XBSX2 where I am unable to create new memory cards. The option to create memory cards is present, but nothing happens when I select it.

**Steps to Reproduce:** Open XBSX2. Navigate to the memory card settings. Attempt to create a new memory card.

**Expected Behavior:** A new memory card should be created.

**Actual Behavior:** Nothing happens when selecting the option to create a new memory card.

 - Console: Series X
 - Version 2.0.6

**Comment by SternXD** [comment]
Thank you for reporting this! I will look into this later tonight.

**Comment by SternXD** [comment]
I have personally tested this myself and I guess I didn't realize that the whole CreateMemoryCard Implimentation was ripped out and put somewhere else it may take a little bit to fix this.

**Comment by SternXD** [comment]
I have fixed this. the fix for this will be in Version 2.0.7.
